import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app import models, schemas
from app.database import get_db

router = APIRouter(tags=["Users"])


@router.get("/users/{user_id}", response_model=schemas.UserOut)
def get_user(user_id: uuid.UUID, db: Session = Depends(get_db)):
    """Read a single user's info."""
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"User {user_id} not found",
        )
    return user


@router.post(
    "/users",
    response_model=schemas.UserOut,
    status_code=status.HTTP_201_CREATED,
)
def create_user(payload: schemas.UserCreate, db: Session = Depends(get_db)):
    """Create a new user. id and createdAt are generated by the database."""
    user = models.User(
        name=payload.name,
        email=payload.email,
        age=payload.age,
        gender=payload.gender,
    )
    db.add(user)
    try:
        db.commit()
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"A user with email {payload.email} already exists",
        )
    db.refresh(user)
    return user


@router.put("/users/{userId}", response_model=schemas.UserOut)
def update_user(
    userId: uuid.UUID, payload: schemas.UserUpdate, db: Session = Depends(get_db)
):
    """Full replace of an existing user's info."""
    user = db.query(models.User).filter(models.User.id == userId).first()
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"User {userId} not found",
        )

    user.name = payload.name
    user.email = payload.email
    user.age = payload.age
    user.gender = payload.gender

    try:
        db.commit()
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"A user with email {payload.email} already exists",
        )
    db.refresh(user)
    return user
